#!/bin/sh

[ "$(stat -c %y ~/.cache/corona 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] && curl -s https://corona-stats.online/us > ~/.cache/corona

grep "Michigan" ~/.cache/corona |
	sed 's/\s*//g ; s/◈//g ; s/│/;/g ; s/%//g' |
	awk -F';' '{print $3 " ("$9") " $5 " (" $7 "%)" }'
